server:
  port: 8000

spring:
  application:
    name: SAUSAGE-API-GATEWAY

  main:
    web-application-type: reactive

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://127.0.0.1:9411/

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id: member-api
          uri: lb://SAUSAGE-MEMBER-API
          predicates:
            - Path=/member/api/auth/**
          filters:
            - RewritePath=/member/(?<path>.*),/$\{path}

        - id: member-api
          uri: lb://SAUSAGE-MEMBER-API
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<path>.*),/$\{path}
            - MbrAuthFilter

        - id: item-api
          uri: lb://SAUSAGE-ITEM-API
          predicates:
            - Path=/item/**
          filters:
            - RewritePath=/item/(?<path>.*),/$\{path}

        - id: cart-share-api
          uri: lb://SAUSAGE-CART-SHARE-API
          predicates:
            - Path=/cart-share/**
          filters:
            - RewritePath=/cart-share/(?<path>.*),/$\{path}

        - id: order-api
          uri: lb://SAUSAGE-ORDER-API
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}

        - id: cart-share-calculation-api
          uri: lb://SAUSAGE-CART-SHARE-CALCULATION-API
          predicates:
            - Path=/cart-share-calculation/**
          filters:
            - RewritePath=/cart-share-calculation/(?<path>.*),/$\{path}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
