server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: SAUSAGE-MEMBER-API
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://127.0.0.1:9411/
