server:
  port: 8761
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: SAUSAGE-EUREKA-SERVER

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
