server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: SAUSAGE-CART-SHARE-CALCULATION-API
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://127.0.0.1:9411/
